config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :customers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'home#index'

  get 'home/index'
  get '/start-a-move', to: "home#start_a_move"
  get '/how-it-works', to: "home#how_it_works", as: :how_it_works
  get '/account-settings', to: "home#account_settings", as: :account_settings
  get '/payment-methods', to: "home#payment_methods", as: :payment_methods

  # Strat url
  get '/contact' => 'home#contact_us', as: :contact_us
  get '/apply' => 'home#apply', as: :apply
  get '/blog', to: "home#new_blog", as: :new_blog

  post '/create_subscribe', to: "customers#create_subscribe", as: :create_subscribe
  get '/signin' => 'customers#sign_in', as: :user_sign_in
  get '/signup', to: "customers#sign_up", as: :user_sign_up
  get '/forget_password', to: "customers#forget_password", as: :forget_password
  match 'auth/:provider/callback', :to => 'home#get_facebook_auth_token', via: [:get, :post]
  get '/moves', to: "home#list_of_moves", as: :list_of_moves
  post '/move_success', to: "home#move_success"
  post '/take_photos', to: "home#take_photos"
  get '/moves/proposals', to: "home#moving_proposals", as: :moving_proposals
  get 'moves/proposal/accept', to: "home#proposal_accept", as: :proposal_accept
  get 'check_promocode', to: "home#check_promo"
  get 'moves/proposal/accept/card_details', to: "home#card_details", as: :card_details
  resources :charges
  # End url

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require "koala"
  def index
    require "browser"
    if session[:fb_token].present?
      @facebook_user = FacebookUser.find_by(uid: session[:fb_token])
      @promo_code = @facebook_user.try(:promo_code).try(:promo_code)
    end
    session[:sharebutton] = nil
  end

  def signin	
  end

  def how_it_works
  end

  def contact_us
    @contact = Contact.new
  end

  def apply
    @customer = Customer.new
  end

  def start_a_move
  end

  def get_facebook_auth_token
    auth = request.env['omniauth.auth']
    token = auth['credentials']['token']
    @facebook_user_data = auth['extra']['raw_info']
    session[:fb_token] = auth['uid']
    facebook_user_access_token = token
    facebook_user_uid = auth['uid']
    if facebook_user_uid.present? && session[:sharebutton].present? && params[:fb].nil?
      if FacebookUser.find_by(uid: auth['uid']).nil?
        @facebook_user = FacebookUser.create(name: @facebook_user_data.name, email: @facebook_user_data.email, fb_access_token: facebook_user_access_token, provider: auth['provider'], uid: auth['uid'])
        if @facebook_user.save
          promo_code = SecureRandom.hex(3)
          caps_promo_code = promo_code.upcase
          @promo_code = @facebook_user.build_promo_code(promo_code: caps_promo_code, is_used: false)
          if @promo_code.save
            CustomerMailer.promo_code(@facebook_user,caps_promo_code).deliver
          end
        end
      else
        @facebook_user = FacebookUser.find_by(uid: auth['uid'])
        promo_code = SecureRandom.hex(3)
        caps_promo_code = promo_code.upcase
        @promo_code = @facebook_user.build_promo_code(promo_code: caps_promo_code, is_used: false)
        if @promo_code.save
          CustomerMailer.promo_code(@facebook_user,caps_promo_code).deliver
        end
      end
      session[:sharebutton] = nil
    end

    if request.env['omniauth.auth']
      @user = User.create_with_omniauth(request.env['omniauth.auth'])
      session[:current_email] = @user.email
      session[:email] = @user.email
      session[:password] = @user.uid
      session[:name] = @facebook_user_data.name
      session[:image] = auth['info']['image']
      session[:token] = auth['credentials']['token']
      session[:uid] = auth['uid']
    end

    respond_to do |format|
      format.html {redirect_to root_path}
      format.json {render :json => { :success => (@user.present? ? true : false), 
                      :email => @user.email, name: @facebook_user_data.name, image: auth['info']['image'], token: auth['credentials']['token'], uid: auth['uid'] }}
    end
    # get auth token
  end

  def move_success
    @move_params = params[:move_params]
    @email = params[:email]
    @date = params[:date]
    CustomerMailer.move_success_mail(@move_params, @email, @date).deliver_now
  end

  def take_photos
    images = params[:move_photo][:avatar].map { |img| {avatar: img} }
    @image = MovePhoto.create(images)
    @images = @image.map{|img| img.avatar.url}
  end

  def moving_proposals
    
  end

  def check_promo
    @fb_user = FacebookUser.find_by(email: session[:current_email])
    if @fb_user.present?
      @check_code = @fb_user.check_promocode(params[:code])
      if @check_code == true
        session[:promocode] = @fb_user.promo_code.promo_code
        render json: {success: "Accepted", message: true, promocode: @fb_user.promo_code.promo_code}
      else
        render json: {error: "Not permitted", message: false}
      end
    else
      render json: {error: "Not permitted", message: false}
    end
  end

  def card_details
  end

  def account_settings
  end

  def payment_methods
  end

end

app/helpers/home_helper.rb
module HomeHelper
	def active_class(link_path)
    request.fullpath == link_path ? "active" : "not_active" 
  end
end

app/views/home/_add_new_card.html.erb
<div id="card_details" class="modal fade" role="dialog">
  <div class="modal-dialog mt-50 page_valid_align new_page_valid_align">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-body" align="center">
        <div align="center">
           <button type="button" class="close cancel-btn" data-dismiss="modal"><span class="badge">x</span></button>
          <img class="new_popup_image" src="/assets/logo2.png">
        </div>
        <div class="popup_content">
          <div class="card-section">
            <div class='row'>
                <div class='col-md-12'>
                  <%= form_tag charges_path, remote: true, authenticity_token: true, method: 'post', id: 'payment-form' do %>
                    <span class="payment-errors"></span>
                    <div class="form-row">
                      <div class='col-xs-12 form-group card required'>
                        <label class='control-label'>Card Number</label>
                        <input class='form-control card-number'type="text" size="20" maxlength="16" data-stripe="number"/ onkeypress='return validateQty(event);'>
                      </div>
                    </div>

                    <div class="col-md-8">
                      <div class="row">
                        <div class="form-row">
                          <div class='col-xs-6 form-group expiration required'>
                           <label class="control-label">Expiration Month</label>
                            <!-- <label class='control-label'>Expiration</label> -->
                            <input class='form-control card-expiry-month' type="text" size="2" maxlength="2" placeholder="MM" data-stripe="exp-month"/ onkeypress='return validateQty(event);'>
                          </div>
                        </div>
                        <div class="form-row">
                          <div class='col-xs-6 form-group expiration required'>
                            <label class='control-label'>Expiration Year </label>
                            <input class='form-control card-expiry-year' type="text" size="4" maxlength="4" placeholder="YY" data-stripe="exp-year"/ onkeypress='return validateQty(event);'>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-4">
                      <div class="row">
                        <div class="form-row">
                          <div class='col-xs-12 form-group cvc required'>
                            <label class='control-label'>CVC</label>
                            <input class='form-control card-cvc'type="text" size="4" maxlength="4" data-stripe="cvc"/ onkeypress='return validateQty(event);'>
                          </div>
                        </div>
                        
                      </div>
                    </div>

                    <button class="new-popup-btn stripe-submit-btn" type="submit">Add</button>
                  <% end %>
                </div>
            </div>
        </div>
          <!-- <button class="new-popup-btn card_detail_save" data-dismiss="modal">Save</button> -->
        </div>
      </div>
    </div>

  </div>
</div>

app/views/home/_apply.html.erb
<%= render "shared/static_header" %>

<section class="slide" style="background:#f2f2f2;">
  <div class="contact">
    <div class="row">
      <div class="col-md-12">
        <div class="contact-cover" style="width:100%;background-image:url(/assets/moober_background_image.jpg);"></div>
        <div class="contact-title">APPLY TO EARN ON MOOBER</div>
      </div>
      <div class="col-md-12">
        <div class="contact-description">
          Ready to increase opportunities and volume for your moving business? Tell us a bit about your company and we'll be in touch within 24 hours.
        </div>
      </div>
  </div>
</section>

<section class="slide">
  <div class="mt-10">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="contact-form text-center apply-contact-form">
          <h1>Get Started</h1>
          <%= form_for @customer, url: customers_path, method: :post do |f| %>
            <% if @customer.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

                <ul>
                <% @customer.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
             <%= f.text_field :full_name, placeholder: "Full Name", required: true, class: "contact-input" %>
             <%= f.text_field :company, placeholder: "Company Name", required: true, class: "contact-input" %>
             <%= f.text_field :site_url, placeholder: "Site Url", required: true, class: "contact-input" %>
             <%= f.email_field :email, placeholder: "Email", required: true, class: "contact-input" %>
             <%= f.text_field :city, placeholder: "City", required: true, class: "contact-input" %>
             <%= f.select :state, options_for_select(Customer.const_get('STATES')), {prompt: 'Select the State'}, class: "contact-input" %>
             <%= f.text_field :phone, placeholder: "Phone Number", required: true,"data-errorMsg"=> "Please, provide a valid phone number", "data-pattern" => "^\d+$", class: "contact-input" %>

             <%#= f.select :find_through, options_for_select(Customer.const_get('FIND_THROUGH')), {prompt: 'How did you hear about us?'} %>
             <%= f.submit "Submit", class: 'submit_btn'%>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="slide contact-company-logo">
  <div class="mt-10">
    <div class="row">
      <%= render "shared/company_logos" %>
    </div>
  </div>
</section>

<section class="slide contact-footer">
  <%= render 'shared/footer' %>
</section>

<%= render 'shared/scrollify' %>
<%= render 'home/top_mbl_side_nav' %>

app/views/home/_contact_us.html.erb
<%= render "shared/static_header" %>

<div class="contact-us">
  <div class="contact">
    <div class="col-md-12 contact-head">
      <div class="contact-cover" style="width:100%;background-image:url(/assets/moober_background_image.jpg);"></div>
      <div class="contact-title">We want to hear from you</div>
    </div>
    <div class="col-md-12 contact-head">
      <div class="contact-description contact-us-desc">
        Have a question for us? Send us a message by filling out the form below and we'll get back to you within 24 hours.
      </div>
    </div>
  </div>
  <div class="contact-mt-10">
    <div class="col-md-6 col-md-offset-3">
      <div class="contact-form text-center">
        <h1>Send us a Message</h1>
        <%= form_for @contact, url: contacts_path, method: :post do |f| %>
        <% if @contact.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

          <ul>
            <% @contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <%= f.text_field :full_name, placeholder: "Full Name", required: true, class: "contact-input" %>
        <%= f.email_field :email, placeholder: "Email", required: true, class: "contact-input" %>
        <%= f.text_field :mobile, placeholder: "Mobile Number", required: true, class: "contact-input" %>
        <%= f.text_area :message, placeholder: "Message", cols: "2", rowws: "3", class: "contact-input" %>
        <%= f.submit "Submit" %>
        <%end%>
      </div>
    </div>
  </div>
  <div class="contact-mt-10">
    <%= render "shared/company_logos" %>
  </div>
  <footer class="contact footer">
    <div class="skyline"><img src="assets/footer.png" width="100%" alt="Moober Solutions"></div>
    <ul class="footer__content">
      <li>
        <ul>
          <li class="footer__item footer__item--address">
            <p><a href="https://www.google.com/maps/place/404+5th+Ave+%237055,+New+York,+NY+10018,+USA/@40.7503617,-73.9858434,17z/data=!3m1!4b1!4m5!3m4!1s0x89c259aa02e83efb:0x8952d4490e23ed2a!8m2!3d40.7503577!4d-73.9836494?hl=en" target="_blank" data-mrf-ignoreLink="true">404 5th Avenue #7055<br>New York, NY 10018</a></p>
            <p>us: <a target="_blank" href="tel:+16467334446" data-mrf-ignoreLink="true">+1 646 733 4446</a></p>
            <p>M-F 9AM-6PM EST</p>
          </li>
        </ul>
      </li>
      <li class="footer__followUs">
        <ul class="emails">
          <li class="footer__item"><a target="_blank" data-mrf-ignoreLink="true" href="mailto:support@moober.com">support@moober.com</a></li>
          <li class="footer__item"><a target="_blank" data-mrf-ignoreLink="true" href="mailto:"></a></li>
        </ul>
        <ul class="data">
          <li class="footer__item"><a href="https://www.instagram.com/moober/" target="_blank"><img src="assets/social/instagram.svg" alt="instagram" data-mrf-ignoreLink="true" target="_blank"></a></li>
          <li class="footer__item"><a href="https://plus.google.com/100353954115280668104" target="_blank"><img src="assets/social/google.svg" alt="google" data-mrf-ignoreLink="true" target="_blank"></a></li>
          <li class="footer__item"><a href="https://www.pinterest.com/moobernyc/?eq=goober&etslf=6100" target="_blank"><img src="assets/social/pinterest.svg" alt="pinterest" data-mrf-ignoreLink="true" target="_blank"></a></li>
          <li class="footer__item"><a href="https://www.facebook.com/pg/Moober-406494646416367/" target="_blank"><img src="assets/social/facebook.svg" alt="facebook" data-mrf-ignoreLink="true"></a></li>
          <li class="footer__item twitter-icon"><a href="https://twitter.com/MooberNYC" target="_blank"><img src="assets/social/twitter.svg" alt="twitter" target="_blank" data-mrf-ignoreLink="true"></a></li>
        </ul>
      </li>
    </ul>
  </footer>
</div>


<%= render 'shared/scrollify' %>
<%= render 'home/top_mbl_side_nav' %>

app/views/home/_featured.html.erb
<section class="slide featuredon">
  <div class="slide__content">
    <div class="slide__title"> Featured on </div>
  </div>
  <div class="slide__media">
    <div class="slide__media--logo">
      <img src="assets/wired.svg" data-src="assets/wired.svg">
    </div>
    <div class="slide__media--logo techcrunch">
      <img src="assets/techcrunch.svg" data-src="assets/techcrunch.svg">
    </div>
    <div class="slide__media--logo">
      <img src="assets/yahoo.svg" data-src="assets/yahoo.svg">
    </div>
    <div class="slide__media--logo">
      <img src="assets/fortune.svg" data-src="assets/fortune.svg">
    </div>
  </div>
</section>

app/views/home/_home.html.erb
<section class="slide bg_video">
  <div class="slide--videoCover">
    <!-- <div class="slide__videoWrapper"> -->
    <div class="slide_videoCover"></div>
    <div id="video-bg" class="slide__videoWrapper">
      <!-- <video autoplay loop muted id="welcomeVideo"> -->
      <video loop autoplay id="bg-video">
        <source src="https://s3-us-west-2.amazonaws.com/moober/moober.mp4" type="video/mp4" type="video/mp4" style="wiidth:100%">
      </video>  
      <img src="/assets/videoposter-mobile.jpg" class="home_image">
    </div>
    <!-- </div> -->
    <div class="slide__content home">
      <h1 class="slide__content__title"> MOVING.</br> MADE.</br> SIMPLE. </h1>
      <div class="play videoPlayer" data-video="#welcomeVideo" data-toggle="modal" data-target="#myModal"> <img src="assets/play-mobile.svg" alt="Play Moober Video"> </div>
      <div class="home_btn_align">
        <button class="contactUs btn-left open_subscripe_popup">Download App</button>
        <button class="contactUs btn-right start_a_move_btn">Start a Move</button>
      </div>
    </div>
  </div>
</section>

app/views/home/_home_how_it_works.html.erb
<section class="slide loop_image_section" id="how_it_work">
  <div class="mt-10">
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-6 loop_image_right">
          <div class="loop_image_content">
            <h1 class="slide__title">How it Works</h1>
            <ol class="list_type">
              <li>
                <div class="slide__text">Enter your pick up address, destination address and a few details about your move.</div>
              </li>
              <li>
                <div class="slide__text">Submit your request to local, verified moving companies who will quickly reply back with competitive quotes.</div>
              </li>
              <li>
                <div class="slide__text">Choose the best offer and confirm your move.</div>
              </li>
              <div class="new-text">Moober provides support and assurance throughout your moving experience.</div>
            </ol>
          </div>
        </div>
        <div class="col-md-6 loop_image_left" id="loop_image_left">
          <div class="slide__media loop_image">
            <img src="assets/360-solution-loop-alpha.gif">
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/_nav.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top"><img src="/assets/logo.png"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <button class="c-hamburger c-hamburger--htx"> <span>toggle menu</span> </button>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/home/_notified.html.erb
<section class="slide notified">
  <div class="mt-10">
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-6 notified_right">
          <div class="slide__title"> Be notified throughout the entire process of your Moober moving experience. </div>
        </div>
        <div class="col-md-6 notified_left" id="notified_left">
          <div class="notified_slide__media" style="margin-top:100px;">
            <img src="assets/01-screen11.png" class="mrf-animable notified_slide__image slide__image--left" data-slide="5" data-animationIn="translate({x:35, y: 0, z:0}, '%', .8)" id="notified_left_1" style="position:absolute" />
            <img src="assets/02-screen1-shadow.png" class="mrf-animable notified_slide__image slide__image--left" data-slide="5" data-animationIn="translate({x:35, y: 0, z:0}, '%', .8)"  style="position:absolute"/>
            <img src="assets/03-screen21.png" class="mrf-animable notified_slide__image slide__image--right" data-slide="5" data-animationIn="translate({x:-35, y: 0, z:0}, '%', .8)" id="notified_left_2" style="position:absolute"/>
            <img src="assets/04-screen2-shadow.png" class="mrf-animable notified_slide__image slide__image--right" data-slide="5" data-animationIn="translate({x:-35, y: 0, z:0}, '%', .8)"  style="position:absolute"/>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/_savings.html.erb
<section class="slide">
  <div class="mt-10">
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-6 saving_section_right">
          <div class="slide__title"> Save cash by comparing quotes. Users who use Moober save an average of 25-35% on their entire move. </div>
        </div>
        <div class="col-md-6 saving_section_left">
          <div class="fasterBrand"> <img src="assets/tentimesfaster.svg" alt="10x Faster"> </div>
          <div class="chartContainer">
            <div class="chartLegend"> $700 for a 1br apartment move </div>
            <div class="chart mrf">
              <div class="greyBar">
                <div class="colorBar mrf-animable" id="top-bar" data-slide="4" data-animationIn="translate({x:0, y: 0, z:0}, '%')" data-animationOut="translate({x:-100, y: 0, z:0}, '%')"></div>
              </div>
            </div>
            <div class="source"> Moober </div>
            <div class="chartLegend"> $1,100 for a 1br apartment move </div>
            <div class="chart others">
              <div class="greyBar">
                <div class="colorBar mrf-animable" id="bottom-bar" data-slide="4" data-animationIn="translate({x:0, y: 0, z:0}, '%')" data-animationOut="translate({x:-100, y: 0, z:0}, '%')"></div>
              </div>
            </div>
            <div class="source"> Average NYC Moving Company </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/_top_mbl_side_nav.html.erb
<div class="mbl-webLateralMenuOverlay"></div>
<div class="mbl-webLateralMenu">
  <ul>
    <li class="user_moves <%= active_class('/moves') %>"><span class="moves-count"><mark>0</mark></span><a href="/moves">Moves</a></li>
    <li class="<%= active_class('/account-settings') %> account_settings"><a href="/account-settings">Account Setting</a></li>
    <li class="<%= active_class('/payment-methods') %> payment_methods"><a href="/payment-methods">Payment Methods</a></li>
    <li><span class="user-login-logut"></span></li>
  </ul>
</div>

app/views/home/how_it_works.html.erb
<%= render 'shared/static_header' %>

<!-- How it Works  -->
<%= render 'how_it_work'%>

<!-- realtime notifications -->
<%= render 'realtime' %>

<!-- footer -->
<%= render 'footer' %>


<%= render 'shared/scrollify' %>
<%= render 'home/top_mbl_side_nav' %>

app/views/home/moving_proposals.html.erb
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCGt1cDImemwSjXZt5hYsCWnDPiC7cQkSE&libraries=places&callback=initProposalMap"></script>
<%= render 'shared/static_header' %>
<section class="moving-results-container">
  <div class="map-prop">
    <div id='proposal_map'></div>
  </div>
  <div class="moving_proposals_results">
    <div class="col-md-12">
      <div class='col-md-3'></div>
      <div class='col-md-6'>
        <div class='col-md-12 success-go-back proposal-go-back'><div class='col-md-3'><div class='go-back-btn'>Go Back</div></div></div>
        <div class="proposal_results">
          
        </div>
      </div>
      <div class='col-md-3'></div>
    </div>
  </div>
</section>
<%= render 'footer' %>
<%= render 'home/top_mbl_side_nav' %>

<script type="text/javascript">
  function defaultMarker(lat, lang){
    var map = new google.maps.Map(document.getElementById('proposal_map'), {
      center: {lat: parseFloat(lat), lng: parseFloat(lang)},
      zoom: 14,
      scrollwheel: false,
      zoomControl: true,
      zoomControlOptions: {
        style: google.maps.ZoomControlStyle.SMALL,
        position: google.maps.ControlPosition.RIGHT_CENTER
      },
      disableDefaultUI: true
    });
    var image = '/assets/map-icon2.png';
    var beachMarker = new google.maps.Marker({
      position: map.getCenter(),
      title: "Moved from here :)",
      map: map,
      icon: image
    });
    var infowindow = new google.maps.InfoWindow({
      content: "<div id='marker-content'><h6>Moved from here :)</h6></div>"
    });
    google.maps.event.addListener(beachMarker, 'click', function() {
      infowindow.open(map,beachMarker);
    });
    infowindow.open(map,beachMarker);
  }
  $(document).ready(function(){
    var request_id = localStorage.getItem('proposal_request');
    
    var lat = localStorage.getItem('proposal_lat');
    var lang = localStorage.getItem('proposal_lang');
    movingProposals(request_id, lat, lang);
    // function initialize() {
    //   var from_add = localStorage.getItem('request_from_add');
    //   address = from_add
    //   // Initialize the Geocoder
    //   geocoder = new google.maps.Geocoder();
    //   console.log(geocoder)
    //   if (geocoder) {
    //     geocoder.geocode({
    //         'address': address
    //     }, function (results, status) {
    //         if (status == google.maps.GeocoderStatus.OK) {
    //             var from_lat = results[0].geometry.location.lat();
    //             localStorage.setItem('proposal_lat', from_lat);
    //             var from_lon = results[0].geometry.location.lng();
    //             localStorage.setItem('proposal_lang', from_lon);
    //         }
    //     });
    //   }
    // }
  });
</script>