config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :customers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'home#index'

  get 'home/index'
  get '/start-a-move', to: "home#start_a_move"
  get '/how-it-works', to: "home#how_it_works", as: :how_it_works
  get '/account-settings', to: "home#account_settings", as: :account_settings
  get '/payment-methods', to: "home#payment_methods", as: :payment_methods

  # Strat url
  get '/contact' => 'home#contact_us', as: :contact_us
  get '/apply' => 'home#apply', as: :apply
  get '/blog', to: "home#new_blog", as: :new_blog

  post '/create_subscribe', to: "customers#create_subscribe", as: :create_subscribe
  get '/signin' => 'customers#sign_in', as: :user_sign_in
  get '/signup', to: "customers#sign_up", as: :user_sign_up
  get '/forget_password', to: "customers#forget_password", as: :forget_password
  match 'auth/:provider/callback', :to => 'home#get_facebook_auth_token', via: [:get, :post]
  get '/moves', to: "home#list_of_moves", as: :list_of_moves
  post '/move_success', to: "home#move_success"
  post '/take_photos', to: "home#take_photos"
  get '/moves/proposals', to: "home#moving_proposals", as: :moving_proposals
  get 'moves/proposal/accept', to: "home#proposal_accept", as: :proposal_accept
  get 'check_promocode', to: "home#check_promo"
  get 'moves/proposal/accept/card_details', to: "home#card_details", as: :card_details
  resources :charges
  # End url

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :mobile, :presence => true, :numericality => true, :length => { :minimum => 10, :maximum => 15 }
end

app/controllers/contacts_controller.rb
class ContactsController < InheritedResources::Base

  def index
    @contact = Contact.new
  end
  def create
    @contact = Contact.new(contact_params)
    respond_to do |format|
      if @contact.save
        AdminUser.all.each do |admin|
          CustomerMailer.contact_email(@contact,admin).deliver
        end
        format.html { redirect_to contact_us_path, notice: 'Successfully sent user details' }
      else
        format.html { render "home/contact_us" }
        # redirect_to :back, notice: @customer.errors
      end
    end
  end

  private

    def contact_params
      params.require(:contact).permit(:full_name, :email, :message,:mobile)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(contact) do |f| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :mobile %>
    <%= f.text_field :mobile %>
  </div>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_field :message %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<%= render "home/contact_us" %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @contact.full_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @contact.mobile %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>